hostname=ip-172-31-9-164.us-east-2.compute.internal
zfs_enable="YES"
zpool_reguid="zroot"
zpool_upgrade="zroot"
dev_aws_disk_enable=YES
ntpd_enable=YES
cloudinit_enable=YES
sshd_enable=YES
ifconfig_ena0=DHCP
pf_enable="NO"
